name: Build and Push
description: Builds and pushes the latest steamcmd image to GitHub Container Registry

inputs:
  tag_name:
    description: "Tag name for the Docker image (or version tag)"
    required: true
  release:
    type: boolean
    description: "Is this a full release?"
    required: true
  github_token:
    description: "GitHub token for pushing to GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/bookworm
        docker build \
          --target=bookworm \
          --tag ghcr.io/cfc-servers/steamcmd:${{ inputs.tag_name }} \
          --tag ghcr.io/cfc-servers/steamcmd:steam \
          .

    - name: Get docker-slim
      shell: bash
      run: |
        SLIM_VERSION=1.40.11

        curl --location --output ds.tar.gz https://github.com/slimtoolkit/slim/releases/download/$SLIM_VERSION/dist_linux.tar.gz
        tar -xvzf ds.tar.gz
        mv dist_linux/* $GITHUB_WORKSPACE
        rm -rfv ds.tar.gz dist_linux/

    - name: Make slim image
      shell: bash
      run: |
        version=${{ inputs.tag_name }}

        $GITHUB_WORKSPACE/docker-slim build \
          --target ghcr.io/cfc-servers/steamcmd:$version \
          --http-probe-off \
          --show-clogs --show-blogs \
          --tag ghcr.io/cfc-servers/steamcmd-slim:$version \
          --tag ghcr.io/cfc-servers/steamcmd-slim:steam \
          --include-path /home/steam/Steam/config/config.vdf \
          --include-path /home/steam/Steam/appcache/appinfo.vdf \
          --exec-file $GITHUB_WORKSPACE/bookworm/slim_script.sh

    - name: Add latest tag
      shell: bash
      run: |
        BASE=ghcr.io/cfc-servers/steamcmd
        version=${{ inputs.tag_name }}

        # Tag image with "0.27" if we push tag "0.27.5"
        # but not if we push tag "0.27-pre5"
        minorVersion=${version%.*}
        if [[ $minorVersion != "0" ]]; then
          echo "::warning:: Tagging with parent minor version: $minorVersion"
          docker tag $BASE:$version $BASE:$minorVersion
          docker tag $BASE-slim:$version $BASE-slim:$minorVersion
        fi

        if [ "${{ inputs.release }}" = "true" ]; then
          echo "::warning:: Tagging this release as the latest!"
          docker tag $BASE:$version $BASE:latest
          docker tag $BASE-slim:$version $BASE-slim:latest
        fi

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Tag and push slim images
      shell: bash
      run: |
        docker push ghcr.io/cfc-servers/steamcmd --all-tags
        docker push ghcr.io/cfc-servers/steamcmd-slim --all-tags
