name: Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/bullseye
          docker build --target=bullseye --tag ghcr.io/cfc-servers/steamcmd:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push image
        run: |
          docker push ghcr.io/cfc-servers/steamcmd --all-tags

