on:
  workflow_dispatch:
  schedule:
    - cron: '18 4 */5 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --match='[0-9]*.[0-9]*.[0-9]*' --match='[0-9]*.[0-9]*' --exclude='*[^0-9.]*')

          echo "Latest tag: $latest_tag"
          echo "tag_name=$latest_tag" >> $GITHUB_OUTPUT

      - name: Push new build
        uses: ./.github/actions/build_and_push
        with:
          tag: ${{ steps.latest_tag.outputs.tag_name }}
          release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
